name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  models: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build steps
        run: |
          echo "Executando build..."
          echo "Adicione seus comandos de build aqui."

  summarize_diff:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Obter diff do commit
        id: get_diff
        run: |
          git fetch origin main
          DIFF=$(git diff origin/main HEAD)
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Resumir diff com GitHub Models
        id: summarize
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -s "https://models.github.ai/inference/chat/completions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -d '{
              "messages": [
                {
                  "role": "user",
                  "content": "Resuma esse diff de código:\n'"${{ steps.get_diff.outputs.diff }}"'"
                }
              ],
              "model": "openai/gpt-4o"
            }')
          SUMMARY=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  notify:
    needs: summarize_diff
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificação para o Teams
        uses: thechetantalwar/teams-notify@v2
        with:
          teams_webhook_url: https://defaultea0c290738d241818750b0b190b604.43.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/006566e0d7b1409d98ab461728de036e/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=XGks5YNdObnxup17kOVPy7mIyC1l0KMP9QpwvDgi7hM
          message: |
            <h1>🚀 Novo deploy no <strong>${{ github.repository }}</strong></h1>
            <p><strong>Branch:</strong> <code>${{ github.ref_name }}</code></p>
            <p><strong>Commit:</strong> <em>${{ github.event.head_commit.message }}</em></p>
            <hr/>
            <p><strong>Resumo do commit:</strong><br/>${{ needs.summarize_diff.outputs.summary }}</p>
